version: '3.7'
services:
  mlflow_server:
    restart: always
    build:
      context: ./pipeline
      dockerfile: Dockerfile.mlflow
      args:
        - "MLFLOW_TRACKING_DIRECTORY=${HOME}/mnt/mlruns"
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - "${HOME}/mnt/mlruns:${HOME}/mnt/mlruns"
    networks:
      - backend
    
volumes:
  mlflow_data: {}


networks:
    backend:
      driver: bridge