version: '3.7'
networks:
    backend:
      driver: bridge

services:
  diabetes_service:
    restart:  always
    build: 
      context: ./deployment
      dockerfile: Dockerfile.diabetes_service
    image: diabetes_service
    container_name: diabetes_service
    environment:
      - MLFLOW_EXPERIMENT_URI=http://mlflow_server:5000
    volumes:
      - "${HOME}/mnt/serve:${HOME}/mnt/serve"
      - "${HOME}/mnt/mlruns:${HOME}/mnt/mlruns"
    ports:
      - "5010:5010"
    networks:
      - backend
        


      