version: '3.7'
services:
  diabetes_service:
    restart:  always
    build: 
      context: ./deployment
      dockerfile: Dockerfile.diabetes_service
    image: diabetes_service
    container_name: diabetes_service
    environment:
      - MLFLOW_EXPERIMENT_URI=http://mlflow_server:5000
    volumes:
      - /tmp/mlopsdb:/tmp/mlopsdb
      - /tmp/mlopsartifacts:/tmp/mlopsartifacts
      - /tmp/store:/tmp/store
      - /tmp/serve:/tmp/serve
    ports:
      - "5010:5010"
    networks:
      - backend
      - external

  send_data_api:
    restart: always
    depends_on:
      - diabetes_service
    build:
      context: ./simulation_business
      dockerfile: Dockerfile.send_data_api
    image:  send_data_api
    container_name: send_data_api
    environment:
      - SERVE_ADDRESS=http://diabetes_service:5010
    networks:
      - external


networks:
    backend:
        driver: bridge
    external:
        driver: bridge


      