FROM python:3.9-slim

WORKDIR /app

COPY ["app.py", "requirements.txt", "./"]
COPY ["utils", "/app/utils"]

RUN pip install -U pip && pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]