FROM python:3.9-slim

COPY requirements_mlflow.txt .
RUN pip install -r requirements_mlflow.txt

RUN mkdir /tmp/mlops
WORKDIR /tmp/mlops

RUN mkdir /tmp/mlopsdb
RUN mkdir /tmp/mlopsartifacts

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:////tmp/mlopsdb/mlflow.db", "--default-artifact-root", "file:///tmp/mlopsartifacts", "--host", "0.0.0.0"]