FROM python:3.9-slim

ARG MLFLOW_TRACKING_DIRECTORY
ENV MLFLOW_TRACKING_DIRECTORY=${MLFLOW_TRACKING_DIRECTORY}

# Install python packages
COPY requirements_mlflow.txt /tmp
RUN pip install -r /tmp/requirements_mlflow.txt
RUN echo ${MLFLOW_TRACKING_DIRECTORY} > test.txt

CMD mlflow server \
    --backend-store-uri sqlite:///${MLFLOW_TRACKING_DIRECTORY}/tracking/mlflow.db \
    --default-artifact-root ${MLFLOW_TRACKING_DIRECTORY}/artifacts \
    --host 0.0.0.0
