FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -U pip
RUN pip install -r requirements.txt

COPY ./ /app/

EXPOSE 5020

CMD ["gunicorn", "--bind", "0.0.0.0:5020", "monitor:app"]